openapi: 3.0.1
info:
  title: Booster Orchestration Services API
  description: ""
  version: ""
servers:
- url: http://127.0.0.1:8002/
paths:
  /sendCode/:
    post:
      tags:
      - sendCode
      operationId: sendCode_create
      responses:
        201:
          description: ""
          content: {}
  /serviceValidation/:
    post:
      tags:
      - serviceValidation
      operationId: serviceValidation_create
      responses:
        201:
          description: ""
          content: {}
  /validateBooster/:
    post:
      tags:
      - validateBooster
      operationId: validateBooster_create
      responses:
        201:
          description: ""
          content: {}
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
